### ISSUE TITLE
Venmo with Drop In back to app automatically without made payment

### ISSUE THREAD

**Issue by bhautikappv** [braintree/braintree-ios-drop-in#15]
I have follow all steps that given at https://developers.braintreepayments.com/guides/drop-in/ios/v4 site as well as https://github.com/braintree/braintree-ios-drop-in

But when I Tap on buy button > open drop in > select venmo > open venmo app > automatically back to app without payment.

Can you please help to solve this issue

please reply me ASAP

Thannk in Advance.

**Comment by lkorth** [comment]
Have you made sure that you are logged in to the Venmo app first and it's not the same issue you posted braintree/braintree_android#138?

**Comment by bhautikappv** [comment]
This issue is for iOS not android.

**Comment by crookedneighbor** [comment]
He's asking if the issue is that the user is not logged into the Venmo app before attempting to initiate the venmo flow.

**Comment by demerino** [comment]
@bhautikappv has your issue been resolved by signing into Venmo?

**Comment by bhautikappv** [comment]
@demerino No, I already logged in into venmo but still getting this issue.

**Comment by demerino** [comment]
Have you configured your Braintree Account for Venmo? 
See: https://developers.braintreepayments.com/guides/venmo/configuration

Are you using your own client token?

**Comment by demerino** [comment]
And can you post the `version` and `build number` of Venmo that was used for testing? Can find in Settings (in Venmo app), all the way at the bottom. It will help us debug.

**Comment by bhautikappv** [comment]
Hey @demerino 
Venmo App Version 6.22.0 (1)

**Comment by demerino** [comment]
@bhautikappv 

We're still looking into this, a few more questions to help us debug:
- what is your return URL scheme?
- what iOS version are you using?
- are you using client tokens or tokenization keys?
- have you contacted Braintree to setup Venmo on your account?

**Comment by bhautikappv** [comment]
- what is your return URL scheme?
-->com.myappname.myappname.payments

- what iOS version are you using?
--> iOS 10.0.2

- are you using client tokens or tokenization keys?
-->Client Token

- have you contacted Braintree to setup Venmo on your account?
-->Yes.

**Comment by demerino** [comment]
@bhautikappv Got it!

We're still not quite sure what the error is. Can you paste the full URL that is sent to your `AppDelegate` (examples below)

```
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
    if ([url.scheme localizedCaseInsensitiveCompare:@"com.your-company.Your-App.payments"] == NSOrderedSame) {
        return [BTAppSwitch handleOpenURL:url options:options];
    }
    return NO;
}

```
OR
```

// If you support iOS 7 or 8, add the following method.
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication
         annotation:(id)annotation {
    if ([url.scheme localizedCaseInsensitiveCompare:@"com.your-company.Your-App.payments"] == NSOrderedSame) {
        return [BTAppSwitch handleOpenURL:url sourceApplication:sourceApplication];
    }
    return NO;
}
```

You should be able to create a breakpoint or simply print the URL which will include the error. We will need the full URL.

Thanks again for your patience.

**Comment by bhautikappv** [comment]
I was used the same code that you paste here. didn't got any error simply back from venmo to app

**Comment by demerino** [comment]
What I meant is `can you insert NSLog statements` so you can send us the URL your app is receiving.

_Example_

```
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
    NSLog("%@", url);
    if ([url.scheme localizedCaseInsensitiveCompare:@"com.your-company.Your-App.payments"] == NSOrderedSame) {
        return [BTAppSwitch handleOpenURL:url options:options];
    }
    return NO;
}

```
OR
```

// If you support iOS 7 or 8, add the following method.
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication
         annotation:(id)annotation {
    NSLog("%@", url);
    if ([url.scheme localizedCaseInsensitiveCompare:@"com.your-company.Your-App.payments"] == NSOrderedSame) {
        return [BTAppSwitch handleOpenURL:url sourceApplication:sourceApplication];
    }
    return NO;
}
```

Note the `NSLog("%@", url);` statements I added. Please send us the output so we can see the error.

**Comment by harirao002** [comment]
Hey @demerino,

I got the same issue as @bhautikappv is described.
My Venmo App Version is 6.21.0(4)
can you found any solution for it.

Thanks

**Comment by demerino** [comment]
@harirao002 

Okay, can you paste me the URL that is being returned to your app so I can see the error? (see my comment just above)

```
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
    NSLog("%@", url);
    if ([url.scheme localizedCaseInsensitiveCompare:@"com.your-company.Your-App.payments"] == NSOrderedSame) {
        return [BTAppSwitch handleOpenURL:url options:options];
    }
    return NO;
}
```

**Comment by harirao002** [comment]
Hey @demerino 

Here is my URL logged from openURL :
com.studopoly.studopoly.payments://x-callback-url/vzero/auth/venmo/error?errorCode=-1004&errorMessage=Unexpected%20error,%20please%20retry%20later.

Please check and let me know what is the issue.

Thanks.

**Comment by bhautikappv** [comment]
My log displays

com.appname.appname.payments://x-callback-url/vzero/auth/venmo/error?errorCode=-1004&errorMessage=Unexpected%20error,%20please%20retry%20later

**Comment by demerino** [comment]
@harirao002 and @bhautikappv 

Thanks for the info - we are looking into it on both the Braintree and Venmo sides. I'll keep you posted.

**Comment by demerino** [comment]
@harirao002 and @bhautikappv

You're testing in Sandbox, correct?

**Comment by harirao002** [comment]
yes

**Comment by demerino** [comment]
Sorry I didn't ask this earlier - what versions of `Braintree` are you using? And double check your settings in `Accept Pay with Venmo` (on the Control Panel). Our initial analysis shows that the Venmo app is unable to fetch a merchant resource from Venmo servers with your Braintree merchant ID.

**Comment by harirao002** [comment]
@demerino 
I used Braintree (4.7.3) and BraintreeDropIn (5.0.1)

**Comment by demerino** [comment]
Got it. When you base64 decode your `client token` do you see the Venmo hash `[@"payWithVenmo"][@"accessToken"]`?

**Comment by harirao002** [comment]
where can i found it?

**Comment by demerino** [comment]
You can find it by base64 decoding your `client token`.

**Comment by harirao002** [comment]
@demerino 
should I need to convert my client token to base64?
where I found [@"payWithVenmo"][@"accessToken"]?
server side or client side(iOS)?

**Comment by demerino** [comment]
You can just share the client token you are using and I will investigate it.

The client token is what you use to start Drop-in. 

```
BTDropInController(authorization: clientTokenOrTokenizationKey, request: request)
```

**Comment by harirao002** [comment]
Here is my client token.

clienttoken = "eyJ2ZXJzaW9uIjoyLCJhdXRob3JpemF0aW9uRmluZ2VycHJpbnQiOiJkM2I0MDcwYzE3OWRiZmFlM2NiN2M5MDczZjRmYWQ4NTMwZDc1YjlkNmRmYmEzMDA5YTJmZjhjZTc3NDczMTQxfGNyZWF0ZWRfYXQ9MjAxNy0wMS0yN1QxNzo1NjowMy43NzQ2NDUyNjkrMDAwMFx1MDAyNm1lcmNoYW50X2lkPXF0enB2NzcycHhmOXR4Z2JcdTAwMjZwdWJsaWNfa2V5PWZyaG03ZjI3aGQ5NXoyeXgiLCJjb25maWdVcmwiOiJodHRwczovL2FwaS5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tOjQ0My9tZXJjaGFudHMvcXR6cHY3NzJweGY5dHhnYi9jbGllbnRfYXBpL3YxL2NvbmZpZ3VyYXRpb24iLCJjaGFsbGVuZ2VzIjpbXSwiZW52aXJvbm1lbnQiOiJzYW5kYm94IiwiY2xpZW50QXBpVXJsIjoiaHR0cHM6Ly9hcGkuc2FuZGJveC5icmFpbnRyZWVnYXRld2F5LmNvbTo0NDMvbWVyY2hhbnRzL3F0enB2NzcycHhmOXR4Z2IvY2xpZW50X2FwaSIsImFzc2V0c1VybCI6Imh0dHBzOi8vYXNzZXRzLmJyYWludHJlZWdhdGV3YXkuY29tIiwiYXV0aFVybCI6Imh0dHBzOi8vYXV0aC52ZW5tby5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tIiwiYW5hbHl0aWNzIjp7InVybCI6Imh0dHBzOi8vY2xpZW50LWFuYWx5dGljcy5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tL3F0enB2NzcycHhmOXR4Z2IifSwidGhyZWVEU2VjdXJlRW5hYmxlZCI6dHJ1ZSwicGF5cGFsRW5hYmxlZCI6dHJ1ZSwicGF5cGFsIjp7ImRpc3BsYXlOYW1lIjoidGVzdCIsImNsaWVudElkIjpudWxsLCJwcml2YWN5VXJsIjoiaHR0cDovL2V4YW1wbGUuY29tL3BwIiwidXNlckFncmVlbWVudFVybCI6Imh0dHA6Ly9leGFtcGxlLmNvbS90b3MiLCJiYXNlVXJsIjoiaHR0cHM6Ly9hc3NldHMuYnJhaW50cmVlZ2F0ZXdheS5jb20iLCJhc3NldHNVcmwiOiJodHRwczovL2NoZWNrb3V0LnBheXBhbC5jb20iLCJkaXJlY3RCYXNlVXJsIjpudWxsLCJhbGxvd0h0dHAiOnRydWUsImVudmlyb25tZW50Tm9OZXR3b3JrIjp0cnVlLCJlbnZpcm9ubWVudCI6Im9mZmxpbmUiLCJ1bnZldHRlZE1lcmNoYW50IjpmYWxzZSwiYnJhaW50cmVlQ2xpZW50SWQiOiJtYXN0ZXJjbGllbnQzIiwiYmlsbGluZ0FncmVlbWVudHNFbmFibGVkIjpmYWxzZSwibWVyY2hhbnRBY2NvdW50SWQiOiI5NmR6eTZ5eDJnaHA5ZnkzIiwiY3VycmVuY3lJc29Db2RlIjoiVVNEIn0sImNvaW5iYXNlRW5hYmxlZCI6ZmFsc2UsIm1lcmNoYW50SWQiOiJxdHpwdjc3MnB4Zjl0eGdiIiwidmVubW8iOiJvZmZsaW5lIn0="

**Comment by demerino** [comment]
Got it - I'm able to reproduce the issue now - so I'll work with the Venmo team on this. 

Thanks again for your patience.

**Comment by harirao002** [comment]
@demerino 
Found any solution?

**Comment by demerino** [comment]
After investigating - it looks like an issue with your settings for Venmo. We'll continue the resolution thru your Support Request that is currently open. I'll leave this issue open until we've confirmed the fix via support.

**Comment by PatNeedham** [comment]
Hi @demerino,

I'm facing this issue as well. When I print the client token and base64 decode it, `"venmo": "offline",` is also included, just like the decoded version of the client token @harirao002 provided. @harirao002 did you end up finding a solution to this problem?

On our Braintree sandbox dashboard we have Venmo payment option enabled:

![image](https://user-images.githubusercontent.com/967811/33215294-39ab9514-d0fd-11e7-8f83-db53dc7d1fe9.png)


What causes the client token to include `"venmo": "offline"`, and is that why nothing happens after returning to the app from Venmo after authorizing the payment?

**Comment by demerino** [comment]
@PatNeedham Seeing `"venmo": "offline"` should not be a problem with the current Pay with Venmo path.

It sounds like you're able to app switch and return successfully... but then it fails. This sounds similar to a recent issue: https://github.com/braintree/braintree-ios-drop-in/issues/61

- Ensure you're using either a Tokenization Key OR Client Token WITH a customer. And that you've updated to the most recent versions of Braintree and Drop-in. There was a recent release that fixed an issue similar to yours that always failed when using a Client Token WITHOUT a customer. Let us know if this is the issue so we can continue to improve the SDK.
- If that doesn't work, put a break point in your app delegate to see the URL used to switch back to your app.
```
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
    NSLog("%@", url);
    if ([url.scheme localizedCaseInsensitiveCompare:@"com.your-company.Your-App.payments"] == NSOrderedSame) {
        return [BTAppSwitch handleOpenURL:url options:options];
    }
    return NO;
}
```

**Comment by PatNeedham** [comment]
Yes I am using a client token with a customer. I had been using the Braintree pod version 4.8.4 and BraintreeDropIn pod version 5.2.1 - upgraded those the the latest (4.9.6 and 5.2.3), still no luck.

The URL being used by that function when returning to the app is in the format "com.companyname.appname.payments://x-callback-url/vzero/auth/venmo/success=?x-source=Venmo&payment-MethodNonce=fake-venmo-account-nonce&username=@our-venmo-username"

Is that what the url is supposed to look like, or does anything stand out that indicates something else might be wrong?

It might also be worth noting that for each time I try to use the Venmo payment method, it stores a new instance of the Venmo payment method to the list of methods for that logged in user (Sandbox Braintree Vault):
![image](https://user-images.githubusercontent.com/967811/33279486-b2066ac2-d36c-11e7-850c-a4788823cc01.png)

**Comment by demerino** [comment]
@PatNeedham What version of iOS (ex: 10.0 or 11.1) is your device using and what version of Venmo does it have installed?

It appears that the nonce is vaulted (based on your screenshot). But the Drop-in callback block isn't called. I would suggest putting a breakpoint here: https://github.com/braintree/braintree_ios/blob/master/BraintreeVenmo/BTVenmoDriver.m#L210

If that doesn't work, maybe you can try a branch we have prepared for the next release: https://github.com/braintree/braintree-ios-drop-in/pull/64

There is a known issue where errors are not being returned correctly in the Venmo/PayPal Drop-in flows.

**Comment by PatNeedham** [comment]
@demerino iOS version 10.3.3 on an iPhone 5c, and the Venmo app installed on it says version 7.9.0 (3).

I tried using #64 by changing the `Podfile` so that the line with BraintreeDopIn looks like this:
```
pod 'BraintreeDropIn', :git => 'https://github.com/braintree/braintree-ios-drop-in.git'
```

After running `pod install` and re-running the application, still the same result as before. I added a few breakpoints, and within that completion block, entering `po error` on the lldb command line returns `nil`, while `po response` looks good, status code 201 (within "headers" field of response, `"X-Request-Id" = "c79b45d7-3476-449a-9d48-52349c365c63";`, including that in case it helps you cross-reference anything).

And entering `po body` inside lldb returns this:
```
<BTJSON:0x16975bf0 value:{
    venmoAccounts =     (
                {
            consumed = 0;
            default = 0;
            description = VenmoAccount;
            details =             {
                cardType = Discover;
                commonId = 9999999999999999999;
                username = venmojoe;
            };
            nonce = "67d636b1-c7b3-0c3d-183d-7ca8977aa505";
            type = VenmoAccount;
        }
    );
}>
```

**Comment by demerino** [comment]
@PatNeedham What does your Drop-in callback look like?

**Comment by dani2906** [comment]
same issue here getting an error for venmo

**Comment by crookedneighbor** [comment]
@dani2906 This issue is from 2017, so if you're having the same issue, please open up a new issue with the details of your integration (SDK version, ios version, etc) or reach out to our support team. https://help.braintreepayments.com/

**Comment by 11095suga** [comment]
Here we are
